banking_dbt:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: dl83766.ap-southeast-7.aws
      user: LAKHANPAL
      password: "Lakh75367536lakh"
      role: accountadmin
      database: banking
      warehouse: COMPUTE_WH
      schema: analytics
      threads: 4